airport/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resource :assertion, only: [:create, :destroy]
  post "/assertions/consume" => "assertions#create", as: :consume
  post "/assertions/logout" => "assertions#destroy", as: :logout
  resource :metadata, only: [:show]
  resources :registrations, only: [:index, :show, :new, :create]
  root to: "registrations#index"
end

airport/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

airport/app/models/metadatum.rb
class Metadatum < ApplicationRecord
  def to_xml
    to_saml.to_xml
  end

  def to_saml
    Saml::Kit::IdentityProviderMetadata.new(metadata)
  end

  class << self
    def register_url(url, verify_ssl: true)
      content = Saml::Kit::DefaultRegistry::HttpApi.new(url, verify_ssl: verify_ssl).get
      register(Saml::Kit::IdentityProviderMetadata.new(content))
    end

    def register(metadata)
      record = Metadatum.find_or_create_by!(entity_id: metadata.entity_id)
      record.metadata = metadata.to_xml
      record.save!
      metadata
    end

    def metadata_for(entity_id)
      Metadatum.find_by!(entity_id: entity_id).to_saml
    rescue ActiveRecord::RecordNotFound => error
      Rails.logger.error(error)
      nil
    end
  end
end

airport/app/models/sp.rb
class Sp
  class << self
    def default(request)
      @sp ||= begin
        url_helpers = Rails.application.routes.url_helpers
        host = "#{request.protocol}#{request.host}:#{request.port}"
        builder = Saml::Kit::ServiceProviderMetadata::Builder.new
        builder.sign = false
        builder.add_assertion_consumer_service(url_helpers.consume_url(host: host), binding: :http_post)
        builder.add_single_logout_service(url_helpers.logout_url(host: host), binding: :http_post)
        builder.build
      end
    end
  end
end

airport/app/models/url_builder.rb
class UrlBuilder
  def http_redirect_url_for(uri, saml_request, relay_state)
    uri.to_s + '?' + {
      'SAMLRequest' => saml_request,
      'RelayState' => relay_state,
    }.map do |(x, y)|
      "#{x}=#{CGI.escape(y)}"
    end.join('&')
  end
end

airport/app/models/user.rb
class User
  attr_reader :id, :email, :attributes

  def initialize(attributes)
    @id = attributes[:id]
    @email = attributes[:email]
    @attributes = attributes
  end

  def name_id_for(name_id_format)
    if Saml::Kit::Namespaces::PERSISTENT == name_id_format
      id
    else
      email
    end
  end
end

airport/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :current_user?

  def current_user(issuer = params[:entity_id])
    return nil unless session[issuer].present?
    User.new(session[issuer].with_indifferent_access)
  end

  def current_user?(issuer)
    current_user(issuer).present?
  end
end

airport/app/controllers/assertions_controller.rb
class AssertionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create, :destroy]

  def create
    saml_binding = sp.assertion_consumer_service_for(binding: :http_post)
    @saml_response = saml_binding.deserialize(params)
    logger.debug(@saml_response.to_xml(pretty: true))
    return render :error, status: :forbidden if @saml_response.invalid?

    session[@saml_response.issuer] = { id: @saml_response.name_id }.merge(@saml_response.attributes)
  end

  def destroy
    if params['SAMLRequest'].present?
      # IDP initiated logout
    elsif params['SAMLResponse'].present?
      saml_binding = sp.single_logout_service_for(binding: :http_post)
      @saml_response = saml_binding.deserialize(params)
      raise ActiveRecordRecordInvalid.new(@saml_response) if @saml_response.invalid?
      session[@saml_response.issuer] = nil
    end
  end

  private

  def sp
    Sp.default(request)
  end
end

airport/app/controllers/metadata_controller.rb
class MetadataController < ApplicationController
  force_ssl if: :ssl_configured?

  def show
    render xml: to_xml, content_type: "application/samlmetadata+xml"
  end

  private

  def to_xml
    Rails.cache.fetch(metadata_url, expires_in: 1.hour) do
      Sp.default(request).to_xml
    end
  end

  def ssl_configured?
    !Rails.env.development?
  end
end

airport/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def index
    @metadatum = Metadatum.all.limit(10)
  end

  def show
    metadatum = Metadatum.find(params[:id])
    render xml: metadatum.to_xml
  end

  def new
  end

  def create
    Saml::Kit.configuration.registry.register_url(params[:url], verify_ssl: Rails.env.production?)
  end
end

airport/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @metadatum = Metadatum.all
  end

  def create
    @saml_builder = builder_for(:login)
    if :http_redirect == params[:binding].to_sym
      redirect_binding = idp.single_sign_on_service_for(binding: :http_redirect)
      @redirect_uri, _ = redirect_binding.serialize(@saml_builder, relay_state: relay_state)
    else
      post_binding = idp.single_sign_on_service_for(binding: :http_post)
      @post_uri, @saml_params = post_binding.serialize(@saml_builder, relay_state: relay_state)
    end
  end

  def destroy
    binding = :http_redirect == params[:binding].to_sym ? :http_redirect : :http_post
    saml_binding = idp.single_logout_service_for(binding: binding)
    @saml_builder = builder_for(:logout)
    @url, @saml_params = saml_binding.serialize(@saml_builder)
  end

  private

  def idp(entity_id = params[:entity_id])
    Saml::Kit.configuration.registry.metadata_for(params[:entity_id])
  end

  def relay_state
    JSON.generate(redirect_to: '/')
  end

  def builder_for(type, entity_id: nil)
    case type
    when :login
      builder = Saml::Kit::AuthenticationRequest::Builder.new
      builder.acs_url = Sp.default(request).assertion_consumer_service_for(binding: :http_post).location
      builder
    when :logout
      Saml::Kit::LogoutRequest::Builder.new(current_user)
    end
  end
end

airport/app/helpers/application_helper.rb
module ApplicationHelper
end

airport/app/views/application/_spinner.html.erb
<div class="spinner"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 25 25"><defs><style>line{fill:none;stroke:#1a1a1a;stroke-linecap:round;stroke-miterlimit:10;stroke-width:2px;}.o25{opacity:0.25;}.o85{opacity:0.85;}.o7{opacity:0.7;}.o55{opacity:0.55;}.o35{opacity:0.35;}</style></defs><line x1="12.5" y1="2" x2="12.5" y2="7.05463"/><line class="o25" x1="12.5" y1="23" x2="12.5" y2="17.94537"/><line class="o85" x1="7.25" y1="3.40674" x2="9.77942" y2="7.78778"/><line class="o25" x1="17.75" y1="21.59326" x2="15.22058" y2="17.21222"/><line class="o25" x1="17.21222" y1="15.22058" x2="21.59326" y2="17.75"/><line class="o7" x1="7.78778" y1="9.77942" x2="3.40674" y2="7.25"/><line class="o25" x1="23" y1="12.5" x2="17.94537" y2="12.5"/><line class="o55" x1="7.05463" y1="12.5" x2="2" y2="12.5"/><line class="o35" x1="7.78778" y1="15.22058" x2="3.40674" y2="17.75"/><line class="o25" x1="21.59326" y1="7.25" x2="17.21222" y2="9.77942"/><line class="o25" x1="9.77942" y1="17.21222" x2="7.25" y2="21.59326"/><line class="o25" x1="17.75" y1="3.40674" x2="15.22058" y2="7.78778"/></svg></div>

airport/app/views/assertions/create.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Received Response</h1>
      <%= render partial: "spinner" %>
      <%= debug @saml_response.to_xhtml %>
    </div>
  </div>
</div>

<%= javascript_tag do %>
  window.onload = function(){
    window.setTimeout(function(){
      window.location.href = '<%= registrations_path %>';
    }, 5000);
  };
<% end %>

airport/app/views/assertions/destroy.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Received Response</h1>
      <%= render partial: "spinner" %>
      <%= debug @saml_response.to_xhtml %>
    </div>
  </div>
</div>

<%= javascript_tag do %>
  window.onload = function(){
    window.setTimeout(function(){
      window.location.href = '<%= registrations_path %>';
    }, 5000);
  };
<% end %>

airport/app/views/assertions/error.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Error</h1>
      <ul>
        <% @saml_response.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

airport/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>